import { NewBadgeDefinition } from '../schema/gamification';

// All 90 badge definitions
export const badgeSeedData: NewBadgeDefinition[] = [
  // ==================== STRENGTH TRAINING BADGES (30) ====================

  // Workout Count Badges (9)
  {
    id: 'strength_workout_1',
    name: 'First Rep',
    description: 'Complete your first workout',
    badgeType: 'strength',
    tier: 'bronze',
    criteria: { type: 'workout_count', value: 1 },
  },
  {
    id: 'strength_workout_5',
    name: 'Getting Started',
    description: 'Complete 5 workouts',
    badgeType: 'strength',
    tier: 'bronze',
    criteria: { type: 'workout_count', value: 5 },
  },
  {
    id: 'strength_workout_10',
    name: 'Committed',
    description: 'Complete 10 workouts',
    badgeType: 'strength',
    tier: 'bronze',
    criteria: { type: 'workout_count', value: 10 },
  },
  {
    id: 'strength_workout_25',
    name: 'Dedicated',
    description: 'Complete 25 workouts',
    badgeType: 'strength',
    tier: 'silver',
    criteria: { type: 'workout_count', value: 25 },
  },
  {
    id: 'strength_workout_50',
    name: 'Iron Regular',
    description: 'Complete 50 workouts',
    badgeType: 'strength',
    tier: 'silver',
    criteria: { type: 'workout_count', value: 50 },
  },
  {
    id: 'strength_workout_100',
    name: 'Century Lifter',
    description: 'Complete 100 workouts',
    badgeType: 'strength',
    tier: 'gold',
    criteria: { type: 'workout_count', value: 100 },
  },
  {
    id: 'strength_workout_250',
    name: 'Iron Warrior',
    description: 'Complete 250 workouts',
    badgeType: 'strength',
    tier: 'gold',
    criteria: { type: 'workout_count', value: 250 },
  },
  {
    id: 'strength_workout_500',
    name: 'Gym Legend',
    description: 'Complete 500 workouts',
    badgeType: 'strength',
    tier: 'platinum',
    criteria: { type: 'workout_count', value: 500 },
  },
  {
    id: 'strength_workout_1000',
    name: 'Iron Immortal',
    description: 'Complete 1000 workouts',
    badgeType: 'strength',
    tier: 'platinum',
    criteria: { type: 'workout_count', value: 1000 },
  },

  // Volume Milestones (8)
  {
    id: 'volume_50k',
    name: 'Heavy Lifter',
    description: 'Lift 50,000 lbs total',
    badgeType: 'strength',
    tier: 'bronze',
    criteria: { type: 'total_volume', value: 50000 },
  },
  {
    id: 'volume_100k',
    name: 'Iron Accumulator',
    description: 'Lift 100,000 lbs total',
    badgeType: 'strength',
    tier: 'bronze',
    criteria: { type: 'total_volume', value: 100000 },
  },
  {
    id: 'volume_250k',
    name: 'Quarter Million',
    description: 'Lift 250,000 lbs total',
    badgeType: 'strength',
    tier: 'silver',
    criteria: { type: 'total_volume', value: 250000 },
  },
  {
    id: 'volume_500k',
    name: 'Half Million Club',
    description: 'Lift 500,000 lbs total',
    badgeType: 'strength',
    tier: 'silver',
    criteria: { type: 'total_volume', value: 500000 },
  },
  {
    id: 'volume_1m',
    name: 'Million Pound Club',
    description: 'Lift 1,000,000 lbs total',
    badgeType: 'strength',
    tier: 'gold',
    criteria: { type: 'total_volume', value: 1000000 },
  },
  {
    id: 'volume_2_5m',
    name: 'Iron Mountain',
    description: 'Lift 2,500,000 lbs total',
    badgeType: 'strength',
    tier: 'gold',
    criteria: { type: 'total_volume', value: 2500000 },
  },
  {
    id: 'volume_5m',
    name: 'Volume King',
    description: 'Lift 5,000,000 lbs total',
    badgeType: 'strength',
    tier: 'platinum',
    criteria: { type: 'total_volume', value: 5000000 },
  },
  {
    id: 'volume_10m',
    name: 'Legendary Volume',
    description: 'Lift 10,000,000 lbs total',
    badgeType: 'strength',
    tier: 'platinum',
    criteria: { type: 'total_volume', value: 10000000 },
  },

  // PR Count Badges (8)
  {
    id: 'pr_1',
    name: 'PR Starter',
    description: 'Set your first PR',
    badgeType: 'strength',
    tier: 'bronze',
    criteria: { type: 'pr_count', value: 1 },
  },
  {
    id: 'pr_5',
    name: 'Breaking Through',
    description: 'Set 5 PRs',
    badgeType: 'strength',
    tier: 'bronze',
    criteria: { type: 'pr_count', value: 5 },
  },
  {
    id: 'pr_10',
    name: 'Record Breaker',
    description: 'Set 10 PRs',
    badgeType: 'strength',
    tier: 'bronze',
    criteria: { type: 'pr_count', value: 10 },
  },
  {
    id: 'pr_25',
    name: 'PR Machine',
    description: 'Set 25 PRs',
    badgeType: 'strength',
    tier: 'silver',
    criteria: { type: 'pr_count', value: 25 },
  },
  {
    id: 'pr_50',
    name: 'Unstoppable',
    description: 'Set 50 PRs',
    badgeType: 'strength',
    tier: 'silver',
    criteria: { type: 'pr_count', value: 50 },
  },
  {
    id: 'pr_100',
    name: 'Century of PRs',
    description: 'Set 100 PRs',
    badgeType: 'strength',
    tier: 'gold',
    criteria: { type: 'pr_count', value: 100 },
  },
  {
    id: 'pr_250',
    name: 'PR Legend',
    description: 'Set 250 PRs',
    badgeType: 'strength',
    tier: 'gold',
    criteria: { type: 'pr_count', value: 250 },
  },
  {
    id: 'pr_500',
    name: 'Record Destroyer',
    description: 'Set 500 PRs',
    badgeType: 'strength',
    tier: 'platinum',
    criteria: { type: 'pr_count', value: 500 },
  },

  // Plate Milestones (9)
  {
    id: 'bench_1_plate',
    name: 'One Plate Bench',
    description: 'Bench 135 lbs',
    badgeType: 'strength',
    tier: 'bronze',
    criteria: { type: 'exercise_weight', exercise: 'bench_press', weight: 135 },
  },
  {
    id: 'bench_2_plate',
    name: 'Two Plate Bench',
    description: 'Bench 225 lbs',
    badgeType: 'strength',
    tier: 'silver',
    criteria: { type: 'exercise_weight', exercise: 'bench_press', weight: 225 },
  },
  {
    id: 'bench_3_plate',
    name: 'Three Plate Bench',
    description: 'Bench 315 lbs',
    badgeType: 'strength',
    tier: 'gold',
    criteria: { type: 'exercise_weight', exercise: 'bench_press', weight: 315 },
  },
  {
    id: 'squat_2_plate',
    name: 'Two Plate Squat',
    description: 'Squat 225 lbs',
    badgeType: 'strength',
    tier: 'bronze',
    criteria: { type: 'exercise_weight', exercise: 'squat', weight: 225 },
  },
  {
    id: 'squat_3_plate',
    name: 'Three Plate Squat',
    description: 'Squat 315 lbs',
    badgeType: 'strength',
    tier: 'silver',
    criteria: { type: 'exercise_weight', exercise: 'squat', weight: 315 },
  },
  {
    id: 'squat_4_plate',
    name: 'Four Plate Squat',
    description: 'Squat 405 lbs',
    badgeType: 'strength',
    tier: 'gold',
    criteria: { type: 'exercise_weight', exercise: 'squat', weight: 405 },
  },
  {
    id: 'deadlift_3_plate',
    name: 'Three Plate Dead',
    description: 'Deadlift 315 lbs',
    badgeType: 'strength',
    tier: 'bronze',
    criteria: { type: 'exercise_weight', exercise: 'deadlift', weight: 315 },
  },
  {
    id: 'deadlift_4_plate',
    name: 'Four Plate Dead',
    description: 'Deadlift 405 lbs',
    badgeType: 'strength',
    tier: 'silver',
    criteria: { type: 'exercise_weight', exercise: 'deadlift', weight: 405 },
  },
  {
    id: 'deadlift_5_plate',
    name: 'Five Plate Dead',
    description: 'Deadlift 495 lbs',
    badgeType: 'strength',
    tier: 'gold',
    criteria: { type: 'exercise_weight', exercise: 'deadlift', weight: 495 },
  },

  // Strength Club Badges (2)
  {
    id: 'club_1000',
    name: '1000 lb Club',
    description: 'Combined S/B/D total of 1000 lbs',
    badgeType: 'strength',
    tier: 'gold',
    criteria: { type: 'powerlifting_total', value: 1000 },
  },
  {
    id: 'club_1500',
    name: '1500 lb Club',
    description: 'Combined S/B/D total of 1500 lbs',
    badgeType: 'strength',
    tier: 'platinum',
    criteria: { type: 'powerlifting_total', value: 1500 },
  },

  // ==================== RUNNING BADGES (40) ====================

  // Distance Milestones (8)
  {
    id: 'run_miles_1',
    name: 'First Mile',
    description: 'Run your first mile',
    badgeType: 'running',
    tier: 'bronze',
    criteria: { type: 'total_distance_miles', value: 1 },
  },
  {
    id: 'run_miles_10',
    name: 'Ten Down',
    description: 'Run 10 total miles',
    badgeType: 'running',
    tier: 'bronze',
    criteria: { type: 'total_distance_miles', value: 10 },
  },
  {
    id: 'run_miles_50',
    name: 'Fifty Miler',
    description: 'Run 50 total miles',
    badgeType: 'running',
    tier: 'bronze',
    criteria: { type: 'total_distance_miles', value: 50 },
  },
  {
    id: 'run_miles_100',
    name: 'Century Runner',
    description: 'Run 100 total miles',
    badgeType: 'running',
    tier: 'silver',
    criteria: { type: 'total_distance_miles', value: 100 },
  },
  {
    id: 'run_miles_250',
    name: 'Road Warrior',
    description: 'Run 250 total miles',
    badgeType: 'running',
    tier: 'silver',
    criteria: { type: 'total_distance_miles', value: 250 },
  },
  {
    id: 'run_miles_500',
    name: 'Distance Demon',
    description: 'Run 500 total miles',
    badgeType: 'running',
    tier: 'gold',
    criteria: { type: 'total_distance_miles', value: 500 },
  },
  {
    id: 'run_miles_1000',
    name: 'Thousand Miler',
    description: 'Run 1000 total miles',
    badgeType: 'running',
    tier: 'gold',
    criteria: { type: 'total_distance_miles', value: 1000 },
  },
  {
    id: 'run_miles_2500',
    name: 'Ultra Runner',
    description: 'Run 2500 total miles',
    badgeType: 'running',
    tier: 'platinum',
    criteria: { type: 'total_distance_miles', value: 2500 },
  },

  // Single Run Distance (7)
  {
    id: 'single_5k',
    name: '5K Finisher',
    description: 'Complete a 5K run',
    badgeType: 'running',
    tier: 'bronze',
    criteria: { type: 'single_run_distance_miles', value: 3.1 },
  },
  {
    id: 'single_10k',
    name: '10K Finisher',
    description: 'Complete a 10K run',
    badgeType: 'running',
    tier: 'bronze',
    criteria: { type: 'single_run_distance_miles', value: 6.2 },
  },
  {
    id: 'single_15k',
    name: '15K Finisher',
    description: 'Complete a 15K run',
    badgeType: 'running',
    tier: 'silver',
    criteria: { type: 'single_run_distance_miles', value: 9.3 },
  },
  {
    id: 'single_half',
    name: 'Half Marathon',
    description: 'Complete a half marathon',
    badgeType: 'running',
    tier: 'silver',
    criteria: { type: 'single_run_distance_miles', value: 13.1 },
  },
  {
    id: 'single_20mi',
    name: '20 Miler',
    description: 'Complete a 20 mile run',
    badgeType: 'running',
    tier: 'gold',
    criteria: { type: 'single_run_distance_miles', value: 20 },
  },
  {
    id: 'single_marathon',
    name: 'Marathon Finisher',
    description: 'Complete a marathon',
    badgeType: 'running',
    tier: 'gold',
    criteria: { type: 'single_run_distance_miles', value: 26.2 },
  },
  {
    id: 'single_ultra',
    name: 'Ultra Runner',
    description: 'Complete an ultra marathon',
    badgeType: 'running',
    tier: 'platinum',
    criteria: { type: 'single_run_distance_miles', value: 31 },
  },

  // Speed Badges - 5K (6)
  {
    id: '5k_sub30',
    name: 'Sub-30 5K',
    description: 'Run a 5K under 30 minutes',
    badgeType: 'running',
    tier: 'bronze',
    criteria: { type: '5k_time', value: 1800 }, // 30 minutes in seconds
  },
  {
    id: '5k_sub27',
    name: 'Sub-27 5K',
    description: 'Run a 5K under 27 minutes',
    badgeType: 'running',
    tier: 'bronze',
    criteria: { type: '5k_time', value: 1620 },
  },
  {
    id: '5k_sub25',
    name: 'Sub-25 5K',
    description: 'Run a 5K under 25 minutes',
    badgeType: 'running',
    tier: 'silver',
    criteria: { type: '5k_time', value: 1500 },
  },
  {
    id: '5k_sub22',
    name: 'Sub-22 5K',
    description: 'Run a 5K under 22 minutes',
    badgeType: 'running',
    tier: 'silver',
    criteria: { type: '5k_time', value: 1320 },
  },
  {
    id: '5k_sub20',
    name: 'Sub-20 5K',
    description: 'Run a 5K under 20 minutes',
    badgeType: 'running',
    tier: 'gold',
    criteria: { type: '5k_time', value: 1200 },
  },
  {
    id: '5k_sub18',
    name: 'Sub-18 5K',
    description: 'Run a 5K under 18 minutes',
    badgeType: 'running',
    tier: 'platinum',
    criteria: { type: '5k_time', value: 1080 },
  },

  // Speed Badges - 10K (5)
  {
    id: '10k_sub60',
    name: 'Sub-60 10K',
    description: 'Run a 10K under 60 minutes',
    badgeType: 'running',
    tier: 'bronze',
    criteria: { type: '10k_time', value: 3600 },
  },
  {
    id: '10k_sub55',
    name: 'Sub-55 10K',
    description: 'Run a 10K under 55 minutes',
    badgeType: 'running',
    tier: 'bronze',
    criteria: { type: '10k_time', value: 3300 },
  },
  {
    id: '10k_sub50',
    name: 'Sub-50 10K',
    description: 'Run a 10K under 50 minutes',
    badgeType: 'running',
    tier: 'silver',
    criteria: { type: '10k_time', value: 3000 },
  },
  {
    id: '10k_sub45',
    name: 'Sub-45 10K',
    description: 'Run a 10K under 45 minutes',
    badgeType: 'running',
    tier: 'gold',
    criteria: { type: '10k_time', value: 2700 },
  },
  {
    id: '10k_sub40',
    name: 'Sub-40 10K',
    description: 'Run a 10K under 40 minutes',
    badgeType: 'running',
    tier: 'platinum',
    criteria: { type: '10k_time', value: 2400 },
  },

  // Speed Badges - Mile (5)
  {
    id: 'mile_sub10',
    name: 'Sub-10 Mile',
    description: 'Run a mile under 10 minutes',
    badgeType: 'running',
    tier: 'bronze',
    criteria: { type: 'mile_time', value: 600 },
  },
  {
    id: 'mile_sub9',
    name: 'Sub-9 Mile',
    description: 'Run a mile under 9 minutes',
    badgeType: 'running',
    tier: 'bronze',
    criteria: { type: 'mile_time', value: 540 },
  },
  {
    id: 'mile_sub8',
    name: 'Sub-8 Mile',
    description: 'Run a mile under 8 minutes',
    badgeType: 'running',
    tier: 'silver',
    criteria: { type: 'mile_time', value: 480 },
  },
  {
    id: 'mile_sub7',
    name: 'Sub-7 Mile',
    description: 'Run a mile under 7 minutes',
    badgeType: 'running',
    tier: 'gold',
    criteria: { type: 'mile_time', value: 420 },
  },
  {
    id: 'mile_sub6',
    name: 'Sub-6 Mile',
    description: 'Run a mile under 6 minutes',
    badgeType: 'running',
    tier: 'platinum',
    criteria: { type: 'mile_time', value: 360 },
  },

  // Elevation Badges (4)
  {
    id: 'elevation_500',
    name: 'Hill Climber',
    description: 'Gain 500ft elevation in a run',
    badgeType: 'running',
    tier: 'bronze',
    criteria: { type: 'single_run_elevation_ft', value: 500 },
  },
  {
    id: 'elevation_1000',
    name: 'Mountain Goat',
    description: 'Gain 1000ft elevation in a run',
    badgeType: 'running',
    tier: 'silver',
    criteria: { type: 'single_run_elevation_ft', value: 1000 },
  },
  {
    id: 'elevation_2500',
    name: 'Summit Seeker',
    description: 'Gain 2500ft elevation in a run',
    badgeType: 'running',
    tier: 'gold',
    criteria: { type: 'single_run_elevation_ft', value: 2500 },
  },
  {
    id: 'elevation_5000',
    name: 'Peak Bagger',
    description: 'Gain 5000ft elevation in a run',
    badgeType: 'running',
    tier: 'platinum',
    criteria: { type: 'single_run_elevation_ft', value: 5000 },
  },

  // Weather Badges (3)
  {
    id: 'weather_rain',
    name: 'Rain Runner',
    description: 'Complete a run in the rain',
    badgeType: 'running',
    tier: 'silver',
    criteria: { type: 'weather_condition', condition: 'rain' },
  },
  {
    id: 'weather_cold',
    name: 'Cold Warrior',
    description: 'Complete a run below 32°F',
    badgeType: 'running',
    tier: 'silver',
    criteria: { type: 'weather_temp_below', value: 32 },
  },
  {
    id: 'weather_heat',
    name: 'Heat Champion',
    description: 'Complete a run above 90°F',
    badgeType: 'running',
    tier: 'silver',
    criteria: { type: 'weather_temp_above', value: 90 },
  },

  // Run Streak Badges (2)
  {
    id: 'run_streak_7',
    name: 'Weekly Runner',
    description: 'Run 7 consecutive days',
    badgeType: 'running',
    tier: 'silver',
    criteria: { type: 'run_streak', value: 7 },
  },
  {
    id: 'run_streak_30',
    name: 'Monthly Runner',
    description: 'Run 30 consecutive days',
    badgeType: 'running',
    tier: 'gold',
    criteria: { type: 'run_streak', value: 30 },
  },

  // ==================== STREAK BADGES (12) ====================

  // Workout Streaks (6)
  {
    id: 'streak_7',
    name: 'One Week Strong',
    description: 'Work out 7 consecutive days',
    badgeType: 'streak',
    tier: 'bronze',
    criteria: { type: 'workout_streak', value: 7 },
  },
  {
    id: 'streak_14',
    name: 'Two Week Warrior',
    description: 'Work out 14 consecutive days',
    badgeType: 'streak',
    tier: 'bronze',
    criteria: { type: 'workout_streak', value: 14 },
  },
  {
    id: 'streak_30',
    name: 'Monthly Dedication',
    description: 'Work out 30 consecutive days',
    badgeType: 'streak',
    tier: 'silver',
    criteria: { type: 'workout_streak', value: 30 },
  },
  {
    id: 'streak_60',
    name: 'Two Month Champion',
    description: 'Work out 60 consecutive days',
    badgeType: 'streak',
    tier: 'gold',
    criteria: { type: 'workout_streak', value: 60 },
  },
  {
    id: 'streak_100',
    name: 'Century Streak',
    description: 'Work out 100 consecutive days',
    badgeType: 'streak',
    tier: 'gold',
    criteria: { type: 'workout_streak', value: 100 },
  },
  {
    id: 'streak_365',
    name: 'Year of Iron',
    description: 'Work out 365 consecutive days',
    badgeType: 'streak',
    tier: 'platinum',
    criteria: { type: 'workout_streak', value: 365 },
  },

  // Weekly Consistency (4)
  {
    id: 'weekly_4',
    name: 'Monthly Consistency',
    description: 'Hit your weekly goal 4 weeks',
    badgeType: 'streak',
    tier: 'bronze',
    criteria: { type: 'weekly_goal_streak', value: 4 },
  },
  {
    id: 'weekly_12',
    name: 'Quarterly Commitment',
    description: 'Hit your weekly goal 12 weeks',
    badgeType: 'streak',
    tier: 'silver',
    criteria: { type: 'weekly_goal_streak', value: 12 },
  },
  {
    id: 'weekly_26',
    name: 'Half Year Habit',
    description: 'Hit your weekly goal 26 weeks',
    badgeType: 'streak',
    tier: 'gold',
    criteria: { type: 'weekly_goal_streak', value: 26 },
  },
  {
    id: 'weekly_52',
    name: 'Year of Dedication',
    description: 'Hit your weekly goal 52 weeks',
    badgeType: 'streak',
    tier: 'platinum',
    criteria: { type: 'weekly_goal_streak', value: 52 },
  },

  // Run Streaks (2) - moved from running section to match count
  {
    id: 'run_streak_100',
    name: '100 Day Runner',
    description: 'Run 100 consecutive days',
    badgeType: 'streak',
    tier: 'platinum',
    criteria: { type: 'run_streak', value: 100 },
  },

  // ==================== HYBRID & PROGRAM BADGES (8) ====================

  // Cross-Training (3)
  {
    id: 'hybrid_athlete',
    name: 'Hybrid Athlete',
    description: 'Complete both lifting and running in a week',
    badgeType: 'hybrid',
    tier: 'bronze',
    criteria: { type: 'hybrid_week', lifts: 1, runs: 1 },
  },
  {
    id: 'iron_runner',
    name: 'Iron Runner',
    description: '100 workouts AND 100 miles',
    badgeType: 'hybrid',
    tier: 'gold',
    criteria: { type: 'hybrid_total', workouts: 100, miles: 100 },
  },
  {
    id: 'ultimate_athlete',
    name: 'Ultimate Athlete',
    description: '500 workouts AND 500 miles',
    badgeType: 'hybrid',
    tier: 'platinum',
    criteria: { type: 'hybrid_total', workouts: 500, miles: 500 },
  },

  // Iron Tiers (2)
  {
    id: 'iron_bronze',
    name: 'Bronze Iron',
    description: 'Consistent training for 3 months',
    badgeType: 'hybrid',
    tier: 'bronze',
    criteria: { type: 'active_months', value: 3 },
  },
  {
    id: 'iron_gold',
    name: 'Golden Iron',
    description: 'Consistent training for 1 year',
    badgeType: 'hybrid',
    tier: 'gold',
    criteria: { type: 'active_months', value: 12 },
  },

  // Program Completion (3)
  {
    id: 'program_1',
    name: 'Program Graduate',
    description: 'Complete your first program',
    badgeType: 'hybrid',
    tier: 'bronze',
    criteria: { type: 'programs_completed', value: 1 },
  },
  {
    id: 'program_3',
    name: 'Program Veteran',
    description: 'Complete 3 programs',
    badgeType: 'hybrid',
    tier: 'silver',
    criteria: { type: 'programs_completed', value: 3 },
  },
  {
    id: 'program_5',
    name: 'Program Master',
    description: 'Complete 5 programs',
    badgeType: 'hybrid',
    tier: 'gold',
    criteria: { type: 'programs_completed', value: 5 },
  },
];

// Total count verification
export const TOTAL_BADGES = badgeSeedData.length;
// Expected: 90 badges
// Strength: 9 workout + 8 volume + 8 PR + 9 plate + 2 club = 36 (but we have 30 per spec)
// Let me recount: 9 + 8 + 8 + 9 + 2 = 36... but spec says 30
// The BADGE_DEFINITIONS.md has 4 plate milestones listed but shows 9 entries
// Let's use the actual data we created
